"""initial schema

Revision ID: 3557cd0fad57
Revises: 
Create Date: 2026-07-14 17:05:28.474372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3557cd0fad57'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('manager_name', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='projectstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=True)
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=10), nullable=False),
    sa.Column('bay', sa.String(length=10), nullable=False),
    sa.Column('seat_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('available', 'occupied', 'reserved', 'maintenance', name='seatstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('floor', 'zone', 'seat_number', name='uq_seat_floor_zone_number')
    )
    op.create_index('ix_seat_floor_zone', 'seats', ['floor', 'zone'], unique=False)
    op.create_index(op.f('ix_seats_floor'), 'seats', ['floor'], unique=False)
    op.create_index(op.f('ix_seats_status'), 'seats', ['status'], unique=False)
    op.create_index(op.f('ix_seats_zone'), 'seats', ['zone'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='employmentstatus', native_enum=False), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=True)
    op.create_index(op.f('ix_employees_name'), 'employees', ['name'], unique=False)
    op.create_index(op.f('ix_employees_project_id'), 'employees', ['project_id'], unique=False)
    op.create_index(op.f('ix_employees_status'), 'employees', ['status'], unique=False)
    op.create_table('seat_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('allocation_status', sa.Enum('active', 'released', name='allocationstatus', native_enum=False), nullable=False),
    sa.Column('allocation_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('released_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seat_allocations_allocation_status'), 'seat_allocations', ['allocation_status'], unique=False)
    op.create_index(op.f('ix_seat_allocations_employee_id'), 'seat_allocations', ['employee_id'], unique=False)
    op.create_index(op.f('ix_seat_allocations_seat_id'), 'seat_allocations', ['seat_id'], unique=False)
    op.create_index('uq_active_allocation_per_employee', 'seat_allocations', ['employee_id'], unique=True, sqlite_where=sa.text("allocation_status = 'active'"), postgresql_where=sa.text("allocation_status = 'active'"))
    op.create_index('uq_active_allocation_per_seat', 'seat_allocations', ['seat_id'], unique=True, sqlite_where=sa.text("allocation_status = 'active'"), postgresql_where=sa.text("allocation_status = 'active'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_allocation_per_seat', table_name='seat_allocations', sqlite_where=sa.text("allocation_status = 'active'"), postgresql_where=sa.text("allocation_status = 'active'"))
    op.drop_index('uq_active_allocation_per_employee', table_name='seat_allocations', sqlite_where=sa.text("allocation_status = 'active'"), postgresql_where=sa.text("allocation_status = 'active'"))
    op.drop_index(op.f('ix_seat_allocations_seat_id'), table_name='seat_allocations')
    op.drop_index(op.f('ix_seat_allocations_employee_id'), table_name='seat_allocations')
    op.drop_index(op.f('ix_seat_allocations_allocation_status'), table_name='seat_allocations')
    op.drop_table('seat_allocations')
    op.drop_index(op.f('ix_employees_status'), table_name='employees')
    op.drop_index(op.f('ix_employees_project_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_seats_zone'), table_name='seats')
    op.drop_index(op.f('ix_seats_status'), table_name='seats')
    op.drop_index(op.f('ix_seats_floor'), table_name='seats')
    op.drop_index('ix_seat_floor_zone', table_name='seats')
    op.drop_table('seats')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
